spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/master
          audiences: account
logging.level:
  org.springframework.web: DEBUG
  org.springframework.security: TRACE